import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

export const frontendAbiDir = path.resolve(__dirname, "../../../src/lib/abi");
export const deploymentsDir = path.resolve(__dirname, "../../deployments");

const EXPORTED = ["ArcadePad", "FeeVault"] as const;
/** The identifier each ABI is exported under in generated.ts. */
const IDENT: Record<(typeof EXPORTED)[number], string> = { ArcadePad: "padAbi", FeeVault: "vaultAbi" };

export type DeploymentRecord = {
  network: string;
  chainId: number;
  deployer: string;
  ponsFactory: string;
  forwarder: string;
  escrow: string;
  pad: string;
  referee: string;
  treasury: string;
  owner: string;
  gameCount: number;
  block: number;
  deployedAt: string;
  txHash: string | null;
};

/**
 * Writes each exported contract's ABI to ../src/lib/abi/<Name>.abi.json
 * (plain JSON, for scripts) and all of them `as const` into
 * ../src/lib/abi/generated.ts, so viem infers argument and return types
 * and the front end can never drift from the contracts.
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  fs.mkdirSync(frontendAbiDir, { recursive: true });
  let ts = "// Generated by `hardhat compile` (contracts/scripts/lib/exportAbi.ts). Do not edit.\n";
  for (const name of EXPORTED) {
    const artifact = await hre.artifacts.readArtifact(name);
    fs.writeFileSync(path.join(frontendAbiDir, `${name}.abi.json`), JSON.stringify(artifact.abi, null, 2) + "\n");
    const ident = IDENT[name];
    ts += `\n/** contracts/${name}.sol */\nexport const ${ident} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  }
  fs.writeFileSync(path.join(frontendAbiDir, "generated.ts"), ts);
}
